export const GET_FRIEND_LIST = "GET_FRIEND_LIST";
export const SIGNIN_ACC_INFO = "SIGNIN_ACC_INFO";

// * POST ACTIONS
export const GET_POSTS = "GET_POSTS";
export const LIKE_TO_POST = "LIKE_POST";
export const ADD_COMMENT_TO_POST = "COMMENT_POST";

// * USER ACTIONS
export const LOGIN_ACCOUNT = "LOGIN_ACCOUNT";
export const LOGOUT_ACCOUNT = "LOGOUT_ACCOUNT";
export const GET_FOLLOWERS = "GET_FOLLOWERS";

// * FUNCTION TYPES ---------
export const CHANGE_CURRENT_TAB = "CHANGE_CURRENT_TAB";
export const SHOW_ADD_POST = "SHOW_ADD_POST";
export const THEME_CONTROL = "THEME_CONTROL";
export const SETTING_MODAL_SHOW = "SETTING_MODAL_SHOW";
export const POST_MODAL_SHOW = "POST_MODAL_SHOW";
export const FOLLOW_MODAL_SHOW = "FOLLOW_MODAL_SHOW";
export const ADD_POST_MODAL = "ADD_POST_MODAL";
export const SELECT_MENU_ITEM = "SELECT_MENU_ITEM";
